#!/usr/bin/env bash

set -eu -o pipefail

IMAGE_MANAGER_DIGEST=$(cat "$1")
shift

eval $(cat bazel-out/stable-status.txt | tr " " "=")

cat <<EOF
IMAGE_MANAGER_DIGEST=${IMAGE_MANAGER_DIGEST}
GIT_COMMIT=${STABLE_BUILD_GIT_COMMIT}
MAJOR_VERSION=${STABLE_BUILD_MAJOR_VERSION}
MINOR_VERSION=${STABLE_BUILD_MINOR_VERSION}
SCM_REVISION=${STABLE_BUILD_SCM_REVISION}
SCM_STATUS=${STABLE_BUILD_SCM_STATUS}
DOCKER_TAG=${STABLE_DOCKER_TAG}
DOCKER_REGISTRY=${STABLE_DOCKER_REGISTRY}
EOF
