apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: cluster-dev
spec:
  infrastructureTemplate:
    apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha4
    kind: HcloudMachineTemplate
    name: cluster-dev-control-plane
  replicas: 1
  version: v1.17.6
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
---
apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha4
kind: HcloudMachineTemplate
metadata:
  name: cluster-dev-control-plane
spec:
  template:
    spec:
      type: cx21
