apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: cluster-dev
  namespace: default
  labels:
    cni: calico-datastore-k8s
    csi: hcloud-csi
    ccm: hcloud-controller-manager-privnet
    metrics-server: metrics-server
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.100.0.0/14"]
    services:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: cluster-dev-control-plane
  infrastructureRef:
    apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
    kind: HcloudCluster
    name: cluster-dev
---
apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
kind: HcloudCluster
metadata:
  name: cluster-dev
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadbalancer:
    type: lb11
    algorithm: round_robin
  locations:
  - fsn1  # first location is used for location of Loadbalancer
  - nbg1
  - hel1
  network:
    cidrBlock: ""
    subnets: []
  sshKeys:
  - name: cluster
  tokenRef:
    key: token
    name: hcloud-token
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: cluster-dev-control-plane
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
    kind: HcloudMachineTemplate
    name: cluster-dev-control-plane-mt-0
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          eviction-hard: nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<15%,imagefs.inodesFree<20%,memory.available<500Mi
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          eviction-hard: nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<15%,imagefs.inodesFree<20%,memory.available<500Mi
  replicas: 3
  version: v1.19.0
---
apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
kind: HcloudMachineTemplate
metadata:
  name: cluster-dev-control-plane-mt-0
  namespace: default
spec:
  template:
    spec:
      type: cx21-ceph
      image: centos-8_k8s-v1.19.0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: cluster-dev-worker-kubeadm-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            eviction-hard: nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<15%,imagefs.inodesFree<20%,memory.available<500Mi
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: cluster-dev-worker-fsn1
  namespace: default
  labels:
    nodepool: worker
spec:
  replicas: 1
  clusterName: cluster-dev
  selector:
    matchLabels:
      nodepool: worker
  template:
    metadata:
      labels:
        nodepool: worker
    spec:
      clusterName: cluster-dev
      version: v1.19.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: cluster-dev-worker-kubeadm-0
      infrastructureRef:
        apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
        kind: HcloudMachineTemplate
        name: cluster-dev-worker-fsn1-mt-0
      failureDomain: fsn1
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: cluster-dev-worker-ngb1
  namespace: default
  labels:
    nodepool: worker
spec:
  replicas: 1
  clusterName: cluster-dev
  selector:
    matchLabels:
      nodepool: worker
  template:
    metadata:
      labels:
        nodepool: worker
    spec:
      clusterName: cluster-dev
      version: v1.19.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: cluster-dev-worker-kubeadm-0
      infrastructureRef:
        apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
        kind: HcloudMachineTemplate
        name: cluster-dev-worker-nbg1-mt-0
      failureDomain: nbg1
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: cluster-dev-worker-hel1
  namespace: default
  labels:
    nodepool: worker
spec:
  replicas: 1
  clusterName: cluster-dev
  selector:
    matchLabels:
      nodepool: worker
  template:
    metadata:
      labels:
        nodepool: worker
    spec:
      clusterName: cluster-dev
      version: v1.19.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: cluster-dev-worker-kubeadm-0
      infrastructureRef:
        apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
        kind: HcloudMachineTemplate
        name: cluster-dev-worker-hel1-mt-0
      failureDomain: hel1
---
apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
kind: HcloudMachineTemplate
metadata:
  name: cluster-dev-worker-fsn1-mt-0
  namespace: default
spec:
  template:
    spec:
      type: cpx11
      image: centos-8_k8s-v1.19.0
---
apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
kind: HcloudMachineTemplate
metadata:
  name: cluster-dev-worker-nbg1-mt-0
  namespace: default
spec:
  template:
    spec:
      type: cpx11
      image: centos-8_k8s-v1.19.0
---
apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
kind: HcloudMachineTemplate
metadata:
  name: cluster-dev-worker-hel1-mt-0
  namespace: default
spec:
  template:
    spec:
      type: cpx11
      image: centos-8_k8s-v1.19.0
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineHealthCheck
metadata:
  name: cluster-dev-worker-unhealthy-5m
spec:
  clusterName: cluster-dev
  maxUnhealthy: 10%
  nodeStartupTimeout: 10m
  selector:
    matchLabels:
      nodepool: worker
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: 300s
  - type: Ready
    status: "False"
    timeout: 300s
